name: lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12.9
      - name: Install ruff
        run: pip install ruff==0.11.5
      - run: ruff format --check && ruff check --no-fix
